apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-api
{{- with .Values.serviceAccounts.api.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-worker
{{- with .Values.serviceAccounts.agentWorker.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: commit-worker
{{- with .Values.serviceAccounts.commitWorker.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: outbox-worker
{{- with .Values.serviceAccounts.outboxWorker.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: retention-worker
{{- with .Values.serviceAccounts.retentionWorker.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandbox
{{- with .Values.serviceAccounts.sandbox.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-migrator
{{- with .Values.serviceAccounts.migration.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eval-worker
{{- with .Values.serviceAccounts.evalWorker.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
automountServiceAccountToken: false
